---
- name: set defaults
  when: ansible_os_family == 'Darwin'
  osx_defaults:
    domain: '{{ item.domain | default(omit) }}'
    key: '{{ item.key }}'
    type: '{{ item.type }}'
    value: '{{ item.value }}'
  with_items: '{{ configs.common }}'
  failed_when: false
  tags:
    - set_defaults

- name: set secret defaults
  when: ansible_os_family == 'Darwin'
  osx_defaults:
    domain: '{{ item.domain | default(omit) }}'
    key: '{{ item.key }}'
    type: '{{ item.type }}'
    value: '{{ item.value }}'
  with_items: '{{ configs.secret }}'
  failed_when: false
  tags:
    - set_defaults
