matrix:
  include:
    - os:
        linux
      dist:
        precise
      sudo:
        false
    - os:
        linux
      dist:
        trusty
      sudo:
        false
    - os:
        linux
      dist:
        precise
      sudo:
        required
    - os:
        linux
      dist:
        trusty
      sudo:
        required
    - os:
        osx
      osx_image:
        xcode8.2
    - os:
        osx
      osx_image:
        xcode8
    - os:
        osx
      osx_image:
        xcode6.4

addons:
  apt:
    sources:
      - sourceline:
          'ppa:ansible/ansible'
    packages:
      - ansible
      - git

language:
  c

git:
  depth:
    3

notifications:
  email:
    false

before_script:
  - env
  - rm -rf $HOME/.bashrc $HOME/.bash_profile $HOME/.gitconfig $HOME/.vim

env:
  global:
    - MAKEFILE=https://raw.githubusercontent.com/sasaplus1/dotfiles/$TRAVIS_BRANCH/Makefile

script:
  - if [ "$TRAVIS_OS_NAME" = 'osx'   ]; then curl -LSfs "$MAKEFILE" | make setup -f -          ; fi
  - if [ "$TRAVIS_OS_NAME" = 'linux' ]; then curl -LSfs "$MAKEFILE" | make clone provision -f -; fi
