language:
  c

git:
  depth:
    3

env:
  global:
    - MAKEFILE=https://raw.githubusercontent.com/sasaplus1/dotfiles/${TRAVIS_BRANCH}/Makefile

addons:
  apt:
    sources:
      - sourceline:
          'ppa:ansible/ansible'
    packages:
      - ansible
      - git

before_script:
  - env

matrix:
  fast_finish:
    true
  include:
    - os:
        linux
      dist:
        precise
      sudo:
        false
      script:
        - curl -LSfs "$MAKEFILE" | make install-brew clone provision -f -
    - os:
        linux
      dist:
        trusty
      sudo:
        false
      script:
        - curl -LSfs "$MAKEFILE" | make install-brew clone provision -f -
    - os:
        linux
      dist:
        precise
      sudo:
        required
      script:
        - curl -LSfs "$MAKEFILE" | make setup -f -
    - os:
        linux
      dist:
        trusty
      sudo:
        required
      script:
        - curl -LSfs "$MAKEFILE" | make setup -f -
    - os:
        osx
      osx_image:
        xcode8.2
      script:
        - curl -LSfs "$MAKEFILE" | make setup -f -
    - os:
        osx
      osx_image:
        xcode8
      script:
        - curl -LSfs "$MAKEFILE" | make setup -f -
    - os:
        osx
      osx_image:
        xcode6.4
      script:
        - curl -LSfs "$MAKEFILE" | make setup -f -

notifications:
  email:
    false
