language: c

matrix:
  include:
    - os: linux
      dist: precise
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode8.2
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode6.4

sudo: required

git:
  depth: 3

before_script:
  - env
  - rm -rf $HOME/.bashrc $HOME/.bash_profile $HOME/.gitconfig $HOME/.vim
script:
  - curl -LSfs https://raw.githubusercontent.com/sasaplus1/dotfiles/master/Makefile | make setup -f -

notifications:
  email: false
