language:
  generic

git:
  depth:
    3

matrix:
  fast_finish:
    true
  include:
    - os:
        linux
      dist:
        trusty
      sudo:
        required
    - os:
        osx
      osx_image:
        xcode9.3beta
    - os:
        osx
      osx_image:
        xcode9.2
    - os:
        osx
      osx_image:
        xcode8
    - os:
        osx
      osx_image:
        xcode6.4

env:
  global:
    - SKIP_TAGS=homebrew_install,homebrew_cask_fetch,homebrew_cask_install

before_script:
  - env

script:
  - curl -LSfs https://raw.githubusercontent.com/sasaplus1/dotfiles/${TRAVIS_BRANCH}/Makefile | make setup -f -

notifications:
  email:
    false
