matrix:
  include:
    - os:
        linux
      dist:
        precise
    - os:
        linux
      dist:
        trusty
    - os:
        osx
      osx_image:
        xcode8.2
    - os:
        osx
      osx_image:
        xcode8
    - os:
        osx
      osx_image:
        xcode6.4

sudo:
  false

addons:
  apt:
    sources:
      - sourceline:
          'ppa:ansible/ansible'
    packages:
      - ansible
      - git

language:
  c

git:
  depth:
    3

notifications:
  email:
    false

before_script:
  - env
  - rm -rf $HOME/.bashrc $HOME/.bash_profile $HOME/.gitconfig $HOME/.vim

script:
  - if [ "$TRAVIS_OS_NAME" = 'osx'   ]; then curl -LSfs https://raw.githubusercontent.com/sasaplus1/dotfiles/master/Makefile | make setup -f -          ; fi
  - if [ "$TRAVIS_OS_NAME" = 'linux' ]; then curl -LSfs https://raw.githubusercontent.com/sasaplus1/dotfiles/master/Makefile | make clone provision -f -; fi
