version: '3.7'

x-base: &base
  build:
    context: .
    dockerfile: Dockerfile
  image: sasaplus1/dotfiles
  init: true

services:
  sh:
    <<: *base
    command:
      - bash
    tty: true
  shellcheck:
    image: koalaman/shellcheck
    init: true
    volumes:
      - .:/mnt
  test:
    <<: *base
    command:
      - bash
      - -c
      - 'rm -f ~/.bashrc && make deploy test && [ "$$(make test)" = "done." ]'
  vint:
    build:
      context: .
      dockerfile: ./dockerfiles/vint/Dockerfile
    image: sasaplus1/dotfiles-vint
    init: true
    volumes:
      - .:/mnt
