---
- name: add apt repositories
  when: ansible_os_family == 'Debian'
  become: yes
  apt_repository:
    repo: '{{ item }}'
  with_items: '{{ repositories }}'
  failed_when: false
  tags:
    - add_apt_repository

- name: change to use JAIST mirror server
  when: ansible_os_family == 'Debian'
  become: yes
  replace:
    dest: /etc/apt/sources.list
    regexp: //archive.ubuntu.com
    replace: //ftp.jaist.ac.jp/pub/Linux
    backup: yes
  failed_when: false
  tags:
    - add_apt_repository
