#!/bin/bash
# NOTE: shebang for shellcheck

__main() {
  unset -f __main

  case "$OSTYPE" in
    darwin*) local -r os=macos ;;
    linux*)  local -r os=linux ;;
    *)       local -r os= ;;
  esac

  #-----------------------------------------------------------------------------

  local -r sh_base_path="$HOME/.cache/sh_base_path"

  if [ -r "$sh_base_path" ]
  then
    # shellcheck disable=SC1090
    source "$sh_base_path"
  else
    # initialize PATHs
    case "$os" in
      macos)
        eval "$(env -i /usr/libexec/path_helper -s)"
        MANPATH="$(env -i /usr/bin/manpath 2>/dev/null || echo '/usr/share/man')"
        export MANPATH
        ;;
      linux)
        # shellcheck disable=SC2016
        PATH="$(env -i /bin/sh -c 'echo $PATH')"
        export PATH
        MANPATH="$(env -i /usr/bin/manpath 2>/dev/null || echo '/usr/local/share/man:/usr/share/man')"
        export MANPATH
        ;;
    esac
    export INFOPATH=
    # cache base PATHs
    command mkdir -p "$HOME/.cache"
    {
      echo '#!/bin/sh'
      printf "export PATH='%s'\n" "$PATH"
      printf "export MANPATH='%s'\n" "$MANPATH"
      printf "export INFOPATH='%s'\n" "$INFOPATH"
    } > "$sh_base_path"
  fi

  #-----------------------------------------------------------------------------

  # aqua {{{
  export AQUA_GLOBAL_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/aquaproj-aqua/aqua.yaml"
  # }}}

  # ghq {{{
  export GHQ_ROOT="$HOME/.ghq"
  # }}}

  #-----------------------------------------------------------------------------

  # Homebrew {{{
  local homebrew_prefix=

  if [ "$os" = 'macos' ]
  then
    [ -d '/usr/local/Homebrew' ] && homebrew_prefix=/usr/local
    # NOTE: my original location
    [ -d "$HOME/Homebrew" ] && homebrew_prefix=$HOME/Homebrew
  fi

  if [ "$os" = 'linux' ]
  then
    [ -d '/home/linuxbrew/.linuxbrew/Homebrew' ] &&
      homebrew_prefix=/home/linuxbrew/.linuxbrew
    [ -d "$HOME/.linuxbrew/Homebrew" ] &&
      homebrew_prefix=$HOME/.linuxbrew
  fi

  if [ -d "$homebrew_prefix" ]
  then
    export INFOPATH="$homebrew_prefix/share/info:$INFOPATH"
    export MANPATH="$homebrew_prefix/share/man:$MANPATH"
    export PATH="$homebrew_prefix/bin:$PATH"

    # NOTE: In POSIX sh, type -t is undefined: SC3045
    # NOTE: brew --prefix is very slow https://github.com/Homebrew/brew/issues/3097
    [ -d "$(dirname "$(dirname "$(command -v brew)")")" ] &&
      export HOMEBREW_PREFIX="$homebrew_prefix"
  fi
  # }}}

  # MacPorts {{{
  local macports_prefix=/opt/local

  if [ "$os" = 'macos' ] && [ -d "$macports_prefix" ]
  then
    export INFOPATH="$macports_prefix/share/info:$INFOPATH"
    export MANPATH="$macports_prefix/share/man:$MANPATH"
    export PATH="$macports_prefix/sbin:$PATH"
    export PATH="$macports_prefix/bin:$PATH"
  fi
  # }}}

  # .local {{{
  local dotlocal_prefix="$HOME/.local"

  [ -d "$dotlocal_prefix" ] && export PATH="$dotlocal_prefix/bin:$PATH"
  # }}}

  #-----------------------------------------------------------------------------

  # aqua {{{
  local -r aqua_home="${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua"
  [ -d "$aqua_home" ] &&
    export PATH="$aqua_home/bin:$PATH"
  # }}}

  # proto {{{
  local -r proto_home="$HOME/.proto"
  [ -d "$proto_home" ] &&
    export PROTO_HOME="$proto_home" &&
    export PATH="$PROTO_HOME/shims:$PROTO_HOME/bin:$PROTO_HOME/tools/node/globals/bin:$PATH"
  # }}}

  # rust/cargo {{{
  local -r cargo_home="$HOME/.cargo"
  # shellcheck disable=SC1091
  [ -d "$cargo_home" ] && source "$cargo_home/env"
  # }}}

  # choosenim - nim/nimble {{{
  [ -d "$HOME/.nimble" ] && export PATH="$HOME/.nimble/bin:$PATH"
  # }}}

  # rbenv {{{
  [ -d "$HOME/.rbenv" ] && export PATH="$HOME/.rbenv/bin:$PATH"
  # }}}

  # go {{{
  local -r go_gopath="$HOME/.go"
  local -r go_gopath_bin="$go_gopath/bin"
  export GOPATH="$go_gopath"
  export PATH="$go_gopath_bin:$PATH"
  # }}}

  # adb/android-platform-tools {{{
  local -r android_platform_tools="$HOME/Library/Android/sdk/platform-tools"
  [ -d "$android_platform_tools" ] && export PATH="$android_platform_tools:$PATH"
  # }}}

  # alacritty {{{
  [ "$os" = 'macos' ] && local -r alacritty="/Applications/Alacritty.app/Contents/MacOS"
  [ -d "$alacritty" ] && export PATH="$alacritty:$PATH"
  # }}}

  # ghostty {{{
  [ "$os" = 'macos' ] && local -r ghostty="/Applications/Ghostty.app/Contents/MacOS"
  [ -d "$ghostty" ] && export PATH="$ghostty:$PATH"
  # }}}

  # wezterm {{{
  [ "$os" = 'macos' ] && local -r wezterm="/Applications/WezTerm.app/Contents/MacOS"
  [ -d "$wezterm" ] && export PATH="$wezterm:$PATH"
  # }}}

  # gibo {{{
  local -r gibo="$GHQ_ROOT/github.com/simonwhitaker/gibo"
  [ -s "$gibo/gibo" ] && export PATH="$gibo:$PATH"
  # }}}

  # vim {{{
  # my Vim for macOS
  # via https://github.com/sasaplus1/macos-vim
  local -r mvim="$GHQ_ROOT/github.com/sasaplus1/macos-vim"
  [ -x "$mvim/usr/bin/vim" ] &&
    export MANPATH="$mvim/share/man:$MANPATH" &&
    export PATH="$mvim/usr/bin:$PATH"
  # }}}

  # tmux {{{
  # my tmux for macOS
  # via https://github.com/sasaplus1/macos-tmux
  local -r tmux="$GHQ_ROOT/github.com/sasaplus1/macos-tmux"
  [ -x "$tmux/usr/bin/tmux" ] &&
    export MANPATH="$tmux/share/man:$MANPATH" &&
    export PATH="$tmux/usr/bin:$PATH"
  # }}}

  # git {{{
  # my git for macOS
  # via https://github.com/sasaplus1/macos-git
  # local -r git="$GHQ_ROOT/github.com/sasaplus1/macos-git"
  # [ -x "$git/usr/bin/git" ] &&
  #   export MANPATH="$git/share/man:$MANPATH" &&
  #   export PATH="$git/usr/bin:$PATH"
  # }}}

  #-----------------------------------------------------------------------------

  # cache user setting PATHs
  command mkdir -p "$HOME/.cache"
  {
    echo '#!/bin/sh'
    printf "export PATH='%s'\n" "$PATH"
    printf "export MANPATH='%s'\n" "$MANPATH"
    printf "export INFOPATH='%s'\n" "$INFOPATH"
    # App paths
    printf "export AQUA_GLOBAL_CONFIG='%s'\n" "$AQUA_GLOBAL_CONFIG"
    printf "export GHQ_ROOT='%s'\n" "$GHQ_ROOT"
    printf "export GOPATH='%s'\n" "$GOPATH"
    [ -n "$HOMEBREW_PREFIX" ] && printf "export HOMEBREW_PREFIX='%s'\n" "$HOMEBREW_PREFIX"
    [ -n "$PROTO_HOME" ] && printf "export PROTO_HOME='%s'\n" "$PROTO_HOME"
  } > "$HOME/.cache/sh_user_path"
}
__main "$@"

# vim:ft=sh:fdm=marker:fen:
