#!/bin/bash
# NOTE: shebang for shellcheck

__main() {
  unset -f __main

  [ -n "$__PROFILE_SOURCED" ] && return
  export __PROFILE_SOURCED=1
  readonly __PROFILE_SOURCED

  local -r sh_path="$(readlink -f "$HOME/.bashrc.d/path")"
  local -r sh_user_path="$HOME/.cache/sh_user_path"
  if [ -r "$sh_user_path" ] && [ "$sh_user_path" -nt "$sh_path" ]
  then
    # shellcheck disable=SC1090
    source "$sh_user_path"
  else
    # shellcheck disable=SC1090
    [ -r "$sh_path" ] && source "$sh_path"
  fi

  #-----------------------------------------------------------------------------

  # history settings
  export HISTSIZE=10000
  export HISTFILESIZE=10000
  export HISTTIMEFORMAT='%Y/%m/%d %T '
  export HISTCONTROL=ignoredups:erasedups

  #-----------------------------------------------------------------------------

  # ssh-agent {{{
  local -r ssh_agent_info="$HOME/.ssh-agent-info"

  # shellcheck disable=SC1090
  [ -r "$ssh_agent_info" ] && source "$ssh_agent_info"

  command ssh-add -l >/dev/null 2>&1
  local -r ssh_add_status=$?

  # ssh-add is unable to contact the authentication agent
  if [ "$ssh_add_status" -eq 2 ]
  then
    # force remove
    unset SSH_AUTH_SOCK SSH_AGENT_PID
    rm -f "$ssh_agent_info"

    if command -v ssh-agent >/dev/null 2>&1
    then
      eval "$(command ssh-agent | grep -v 'echo')"
      {
        printf 'SSH_AUTH_SOCK=%s; export SSH_AUTH_SOCK;\n' "$SSH_AUTH_SOCK"
        printf 'SSH_AGENT_PID=%s; export SSH_AGENT_PID;\n' "$SSH_AGENT_PID"
      } > "$ssh_agent_info"
    fi
  fi
  # }}}

  #-----------------------------------------------------------------------------

  # stop flow mode (disable C-s and C-q)
  # stty stop undef
  # stty start undef
  type stty >/dev/null 2>&1 && stty -ixon

  type vi >/dev/null 2>&1 && export EDITOR=vi
  type vim >/dev/null 2>&1 && export EDITOR=vim
  type less >/dev/null 2>&1 && export PAGER=less

  # NOTE: `$ man bash` outputs `UNSUPP: unsupported control character: 0x7` error
  # https://github.com/orgs/Homebrew/discussions/2506
  if type bat >/dev/null 2>&1
  then
    set -- "$SHELL -c 'col -bx | bat -l man --style=plain --paging=always'"
    # highlighting man page with bat
    export MANPAGER="$*"
  elif [ "$EDITOR" = 'vim' ]
  then
    set -- "$SHELL -c 'col -bx | vim -u NONE -NR -c \"se hls is nolist noma nomod sc scs wrap ft=man | syntax enable\" -'"
    # use vim
    export MANPAGER="$*"
  fi
}
__main "$@"

# vim:ft=sh:fdm=marker:fen:
