---
- name: add taps
  homebrew_tap:
    tap: '{{ item.repo }}'
  with_items: '{{ taps.common }}'
  failed_when: false
  tags:
    - homebrew_tap

- name: add taps for macOS
  when: ansible_os_family == 'Darwin'
  homebrew_tap:
    tap: '{{ item.repo }}'
  with_items: '{{ taps.macos }}'
  failed_when: false
  tags:
    - homebrew_tap
