require('nvim-treesitter.configs').setup {
  auto_install = false,
  ensure_installed = 'all',
  ignore_install = {
    -- https://github.com/nvim-treesitter/nvim-treesitter/issues/7941
    -- https://github.com/nvim-treesitter/nvim-treesitter/discussions/7942
    "ipkg",
  },
  -- ensure_installed = {
  --   "query", -- required
  -- },
  -- ensure_installed = "all",
  -- ensure_installed = {
  --   "awk",
  --   "bash",
  --   "c",
  --   "c_sharp",
  --   "cmake",
  --   "commonlisp",
  --   "cpp",
  --   "css",
  --   "csv",
  --   "diff",
  --   "dockerfile",
  --   "git_config",
  --   "git_rebase",
  --   "gitattributes",
  --   "gitcommit",
  --   "gitignore",
  --   "go",
  --   "graphql",
  --   "groovy",
  --   "html",
  --   "java",
  --   "javascript",
  --   "jq",
  --   "jsdoc",
  --   "json",
  --   "json5",
  --   "jsonc",
  --   "kotlin",
  --   "liquid",
  --   "lua",
  --   "luadoc",
  --   "luap",
  --   "make",
  --   "markdown",
  --   "markdown_inline",
  --   "mermaid",
  --   "nim",
  --   "nim_format_string",
  --   "objc",
  --   "pascal",
  --   "php",
  --   "php_only",
  --   "phpdoc",
  --   "printf",
  --   "properties",
  --   "pug",
  --   "regex",
  --   "robots",
  --   "ruby",
  --   "rust",
  --   "scala",
  --   "scss",
  --   "sql",
  --   "ssh_config",
  --   "swift",
  --   "tcl",
  --   "tmux",
  --   "tsv",
  --   "tsx",
  --   "typescript",
  --   "vim",
  --   "vimdoc",
  --   "vue",
  --   "xml",
  --   "yaml",
  --   "zig"
  -- },
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
  indent = {
    enable = true,
  },
  sync_install = false,
}
