{ pkgs, pkgs-unstable, lib }:
[
  pkgs.age
  pkgs-unstable.ast-grep
  pkgs-unstable.atuin
  pkgs.bash
  pkgs.bash-completion
  pkgs.bash-preexec
  pkgs.bat
  pkgs.bitwarden-cli
  pkgs.bws
  pkgs-unstable.claude-code
  pkgs-unstable.codex
  pkgs.curl
  pkgs.delta
  pkgs-unstable.direnv
  pkgs.fac
  pkgs.fd
  pkgs.fswatch
  pkgs.fzf
  pkgs-unstable.gh
  pkgs.ghq
  pkgs.gibo
  pkgs.git
  pkgs.git-crypt
  pkgs-unstable.betterleaks
  pkgs-unstable.gitleaks
  pkgs.gnupg
  pkgs.glow
  pkgs.gron
  pkgs.jq
  pkgs-unstable.jujutsu
  pkgs.mmv-go
  pkgs-unstable.neovim
  pkgs.nmap
  pkgs-unstable.pinact
  pkgs-unstable.proto
  pkgs.ripgrep
  pkgs.rsync
  pkgs.sops
  pkgs.tig
  pkgs.tmux
  pkgs.yq-go
  pkgs.zoxide
] ++ lib.optionals pkgs.stdenv.isDarwin [
  pkgs-unstable.container
  pkgs.mas
] ++ lib.optionals pkgs.stdenv.isLinux [
  pkgs.trash-cli
  pkgs.xsel
]
