---
- name: clone vim plugin repositories
  git:
    repo: '{{ item.repo }}'
    dest: '{{ item.dest }}'
  with_items: '{{ repositories }}'
  tags:
    - vim

- name: build vimproc library
  command: 'make'
  args:
    chdir: '{{ vimproc_directory }}'
  tags:
    - vim
