---
- hosts: 127.0.0.1

  vars:
    pkg_config_dirs:
      - '{{ homebrew_dir }}/lib64/pkgconfig'
      - '{{ homebrew_dir }}/lib/pkgconfig'
      - '{{ lookup("env", "PKG_CONFIG_PATH") }}'
    ld_library_dirs:
      - '{{ homebrew_dir }}/lib64'
      - '{{ homebrew_dir }}/lib'
      - '{{ lookup("env", "LD_LIBRARY_PATH") }}'

  environment:
    PATH:
      '{{ homebrew_dir }}/bin:{{ lookup("env", "PATH") }}'
    PKG_CONFIG_PATH:
      '{{ pkg_config_dirs | join(":") }}'
    LD_LIBRARY_PATH:
      '{{ ld_library_dirs | join(":") }}'
    HOMEBREW_CASK_OPTS:
      '--caskroom={{ caskroom_dir }}'

  roles:
    - { role: 'git_remote'            }
    - { role: 'dotdirectories'        }
    - { role: 'dotfiles'              }
    - { role: 'homebrew_install'      }
    - { role: 'homebrew_cask_fetch'   }
    - { role: 'homebrew_cask_install' }
    - { role: 'urxvt'                 }
    - { role: 'vim'                   }
