- hosts: 127.0.0.1

  vars:
    pkg_config_dirs:
      - "{{ homebrew_dir }}/lib64/pkgconfig"
      - "{{ homebrew_dir }}/lib/pkgconfig"
      - "{{ lookup('env', 'PKG_CONFIG_PATH') }}"
    ld_library_dirs:
      - "{{ homebrew_dir }}/lib64"
      - "{{ homebrew_dir }}/lib"
      - "{{ lookup('env', 'LD_LIBRARY_PATH') }}"

  roles:
    - { role: 'dotfiles'         }
    - { role: 'dotfiles_remotes' }
    - { role: 'homebrew'         }
    - { role: 'homebrew_cask'    }
    - { role: 'node.js'          }
    - { role: 'ruby'             }
    - { role: 'urxvt'            }
    - { role: 'vim'              }

  environment:
    PATH:
      "{{ homebrew_dir }}/bin:{{ lookup('env', 'PATH') }}"
    PKG_CONFIG_PATH:
      "{{ pkg_config_dirs | join(':') }}"
    LD_LIBRARY_PATH:
      "{{ ld_library_dirs | join(':') }}"
    HOMEBREW_CASK_OPTS:
      "--caskroom={{ caskroom_dir }}"
