---
packages:

  common:
    - { name: 'bash-completion'                                                                              }
  # - { name: 'ctags'                                                                                        }
  # - { name: 'docker'                                                                                       }
    - { name: 'ghq'                                                                                          }
    - { name: 'ghs'                                                                                          }
    - { name: 'gibo'                                                                                         }
    - { name: 'git',                  install_options: 'with-brewed-curl,with-brewed-openssl,without-tcl-tk' }
    - { name: 'go'                                                                                           }
    - { name: 'hub'                                                                                          }
  # - { name: 'jq'                                                                                           }
  # - { name: 'mercurial'                                                                                    }
    - { name: 'mitmproxy'                                                                                    }
    - { name: 'monochromegane/pt/pt'                                                                         }
  # - { name: 'neovim'                                                                                       }
    - { name: 'nginx-full',           install_options: 'with-subs-filter-module'                             }
  # - { name: 'nodebrew'                                                                                     }
    - { name: 'peco'                                                                                         }
    - { name: 'pyenv'                                                                                        }
    - { name: 'ranger'                                                                                       }
    - { name: 'rbenv'                                                                                        }
    - { name: 'rbenv-default-gems'                                                                           }
    - { name: 'redis'                                                                                        }
    - { name: 'ripgrep'                                                                                      }
    - { name: 'ruby-build'                                                                                   }
    - { name: 'sqlite'                                                                                       }
  # - { name: 'textql'                                                                                       }
  # - { name: 'the_silver_searcher'                                                                          }
    - { name: 'tig'                                                                                          }
    - { name: 'tmux'                                                                                         }
    - { name: 'tree'                                                                                         }
  # - { name: 'vcprompt'                                                                                     }
    - { name: 'z'                                                                                            }

  macos:
  # - { name: 'android-platform-tools'     }
  # - { name: 'brew-cask'                  }
  # - { name: 'closure-linter'             }
  # - { name: 'flow'                       }
  # - { name: 'fswatch'                    }
    - { name: 'mas'                        }
    - { name: 'reattach-to-user-namespace' }
  # - { name: 'unar'                       }
