name: test

on:
  - push
  - pull_request

jobs:
  deploy-and-test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    name: deploy & test (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - macos-15
          - ubuntu-22.04
          - ubuntu-24.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: rm -f ~/.bash{_logout,_profile,rc} ~/.docker/config.json ~/.gitconfig ~/.profile
      - run: make deploy
      - run: make test
      - run: test "$(make test)" = 'done.'
  home-manager:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    name: home-manager (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31.10.4
        with:
          nix_path: nixpkgs=channel:nixos-25.11
      - uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13
      - run: make install-home-manager
        working-directory: home-manager
      - run: make build
        working-directory: home-manager
  shellcheck:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - id: find-scripts
        run: echo "files=$(find bash -type f | sort | tr '\n' ' ')" | tee -a "$GITHUB_OUTPUT"
      - uses: docker://koalaman/shellcheck:stable@sha256:bb596a0d169b85ddd81d8b6d3a2ff6d5baf5fca10b97f575ebc647c3dff62b3d
        with:
          args: ${{ steps.find-scripts.outputs.files }}
